ubus: fix shadow local variable
Fix leftover shadowed local variable in ubus code from commit a170d63874f2.

src/ubus.c:130:38: error: declaration of 'a' shadows a previous local [-Werror=shadow=local]
  130 |                 struct dhcpv6_lease *a, *border;
      |                                      ^
src/ubus.c:118:15: note: shadowed declaration is here
  118 |         void *a;
      |               ^

Fixes: a170d63874f2 ("src: fix shadowed local variables")
Signed-off-by: Álvaro Fernández Rojas <noltari@gmail.com>